version: "3.9"

services:
  sablier:
    image: sablierapp/sablier:1.10.1
    container_name: sablier
    command:
      - start
      - --provider.name=docker
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
    networks:
      - traefik-networks

  # Simple service to test sablier using the whoami image
  whoami:
    image: traefik/whoami:latest
    container_name: whoami_sablier
    restart: unless-stopped
    networks:
      - traefik-networks

networks:
  default:
  traefik-networks:
    external: true

