global:
  checkNewVersion: false
  sendAnonymousUsage: false

log:
  level: INFO  # Log level (DEBUG, INFO, WARN, ERROR)

api:
  dashboard: false
  insecure: true

entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
  websecure:
    address: ":443"

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
  file:
    # setup the dynamic config file path and enable watch so if the file changed, traefik will auto reload it
    filename: "/etc/traefik/dynamic-config.yaml"
    watch: true 

# Setup the certificates resolvers
certificatesResolvers:
  myresolver: # make sure the name here match the certResolver name that we use at the routers setup
    acme:
      email: YOUR_EMAIL_HERE
      storage: "/letsencrypt/acme.json"
      httpChallenge:
        entrypoint: web # Traefik will use the web entrypoint to listen to the http challenge requests

# SETUP THE PLUGIN  (make sure the plugin is already enabled at the traefik dashboard https://doc.traefik.io/traefik/plugins/overview/)
experimental:
  plugins:
    sablier:
      moduleName: "github.com/sablierapp/sablier"
      version: "v1.10.1"